const images = {
  allInterview: require('../icons/allInterview.png'),
  arrow: require('../icons/arrow.png'),
  back: require('../icons/back.png'),
  calender: require('../icons/calender.png'),
  CV: require('../icons/cv.png'),
  eye_hide: require('../icons/eye_hide.png'),
  eye: require('../icons/eye.png'),
  files: require('../icons/files.png'),
  filter: require('../icons/filter.png'),
  idea: require('../icons/idea.png'),
  interview_Today: require('../icons/interview_Today.png'),
  interview: require('../icons/Interview.png'),
  Leads: require('../icons/Leads.png'),
  Line: require('../icons/Line.png'),
  logo: require('../icons/logo.png'),
  mark: require('../icons/mark.png'),
  menu: require('../icons/menu.png'),
  Notification_Icon: require('../icons/Notification_Icon.png'),
  notification: require('../icons/notification.png'),
  notification1: require('../icons/notification1.png'),
  pen: require('../icons/pen.png'),
  power_off: require('../icons/power-off.png'),
  Profile_icon: require('../icons/Profile_Icon.png'),
  profile: require('../icons/profile.png'),
  Setting: require('../icons/Settings.png'),
  small_icon: require('../icons/small-icon.png'),
  testTask: require('../icons/testTask.png'),
  verticalLine: require('../icons/verticalLine.png'),
};
export default images;
